// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIJINvRgwj6oBcQdVt7UA4C8gQSPk-hRc',
    appId: '1:619599118841:android:1cd5a466a3571ee943bd28',
    messagingSenderId: '619599118841',
    projectId: 'olio-f1da1',
    storageBucket: 'olio-f1da1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQC2FwJd7HEwY8muOIxPR3LcrnmioinUo',
    appId: '1:619599118841:ios:8e39725af10148b143bd28',
    messagingSenderId: '619599118841',
    projectId: 'olio-f1da1',
    storageBucket: 'olio-f1da1.firebasestorage.app',
    androidClientId: '619599118841-04mmtuumu11oh0vf8k95nqsejbtve71h.apps.googleusercontent.com',
    iosClientId: '619599118841-gbotv6vma2ulgncjie0hsnrn6ssnbdvr.apps.googleusercontent.com',
    iosBundleId: 'in.primathon.personalFinanceManager',
  );
}
