// PLACEHOLDER — replace by running `flutterfire configure`.
//
// This file is normally generated by the FlutterFire CLI and contains your
// Firebase project's (non-secret) client configuration. The values below are
// intentionally fake so the project still compiles; Firebase initialization is
// guarded in `main()`, so the app runs fine until you generate the real file:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// See README (Firebase setup) for the full steps.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return _placeholder;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
        return _placeholder;
      default:
        return _placeholder;
    }
  }

  static const FirebaseOptions _placeholder = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'replace-me',
  );
}
